name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        if: ${{ !startsWith(matrix.os, 'ubuntu') }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}/tests"
          CIBW_BEFORE_BUILD_LINUX: "curl -o rustup.sh --proto '=https' --tlsv1.2 https://sh.rustup.rs && sh ./rustup.sh -y"
          CIBW_ENVIRONMENT: PATH=$PATH:$HOME/.cargo/bin
          CIBW_SKIP: "*musl*"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
